name: main
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Package Building
        run: npm ci
        run: npm run build
        env:
          CI: true
